name: PRE_WHEELS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  PRE:
    uses: ./.github/workflows/test_template.yml
    with:
      runs-on: '["ubuntu-latest", ]'
      python-version: '["3.10", ]'
      use-pre: true
      extra-depends: scikit_learn scipy statsmodels pandas tables